name: pantheon-wp-best-practices

recipe: pantheon

config:
  framework: wordpress
  site: pantheon-wp-best-practices
  id: 094f4627-a25e-4d60-8d5b-a3d99a7232bf
  xdebug: true
  webroot: web
  php: '7.2'

services:

  # Spin up a PHP CI service for Behat, PHPUnit, etc.
  ci_php:
    type: php:custom
    overrides:
      image: quay.io/pantheon-public/build-tools-ci:4.x

# Additional "lando" commands
tooling:
  composer:
    service: ci_php
  wp:
    service: appserver
  composer-install:
    description: Install Composer dependencies
    cmd: ./bin/install-composer-dependencies.sh
    service: ci_php
  code-sniff:
    description: Run Code Sniffing
    cmd: ./vendor/bin/phpcs --extensions=php --runtime-set ignore_warnings_on_exit true ./web/wp-content/themes/twentyseventeen-child/* ./tests/*
    service: ci_php
  code-sniff-fix:
    description: Fix Code Sniffing
    cmd: ./vendor/bin/phpcbf --ignore=*/.git*/*,*/node_modules/* --extensions=php ./web/wp-content/themes/twentyseventeen-child/* ./tests/*
    service: ci_php
  unit-test:
    description: Run unit tests
    cmd: composer -n unit-test
    service: ci_php
  wordhat:
    description: Run WordHat
    cmd: ./bin/local-behat-headless-chrome.sh
    service: ci_php
  restore-db:
    description: Restore the database
    cmd: ./bin/restore-db.sh
    service: ci_php
  export-db:
    description: export the database
    cmd: ./bin/export-db.sh
    service: appserver
  wordhat-commands:
    description: List WordHat commands
    cmd: composer -n wordhat-scenarios
    service: ci_php