name: pantheon-wp-best-practices
recipe: pantheon
config:
  framework: wordpress
  site: pantheon-wp-best-practices
  id: 094f4627-a25e-4d60-8d5b-a3d99a7232bf
  xdebug: true
  webroot: web
  php: '7.1'

services:
  
  # Spin up a node service so we can run gulp
  node:
    type: node:8.9
    ssl: true
    globals:
      gulp-cli: "latest"
      gulp: "next"

# Provide some tooling routes
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  composer:
    service: appserver
  wp:
    service: appserver

# Automate some build steps that should happen after every start
events:
  post-start:
    # Run composer every time appserver is started
    - appserver: cd $LANDO_MOUNT && ./bin/install-composer-dependencies.sh
    # Run gulp every time node is started
    # This is commented out due to node-sass needing it's binary rebuilt to run in Lando
    # Since that is too heavy of an operation I run gulp locally
    #- node: cd $LANDO_MOUNT && ./.circleci/build-gulp-assets.sh
