name: pantheon-wp-best-practices
recipe: pantheon
config:
  framework: wordpress
  site: pantheon-wp-best-practices
  id: 094f4627-a25e-4d60-8d5b-a3d99a7232bf
  xdebug: true
  webroot: web
  php: '7.1'

proxy:
  node:
    - wp-best-practices.lndo.site:3000

services:
  # Spin up a node service so we can run gulp
  node:
    type: node:8.9
    node: '8.9'
    ssl: true
    globals:
      gulp-cli: "latest"
      gulp: "next"
    overrides:
      services:
        ports: [3000:3000]

# Provide some tooling routes
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  composer:
    service: appserver
  wp:
    service: appserver
  composer-install:
    description: Install Composer dependencies
    cmd: ./bin/install-composer-dependencies.sh
    service: appserver
  gulp-build:
    description: Install npm dependencies and run gulp
    cmd: ./.circleci/build-gulp-assets.sh
    service: node

# Automate some build steps that should happen after every start
events:
  post-start:
    # Run gulp every time node is started
    - node: "cd $LANDO_MOUNT && ./.circleci/build-gulp-assets.sh"
    # Run composer every time appserver is started
    - appserver: "cd $LANDO_MOUNT && ./bin/install-composer-dependencies.sh"